# Site wide configuration

title: "Ser hoy uno"
description: "Números palabras"
logo: ShU.png # 120x120px default image used for summary
teaser: escritos.jpeg # 400x250px default teaser used in grid
locale: es
url:
feed:
  path: feed.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Fernando Rivas"
  email: fenandos@hotmail.com
  twitter: @fenandosr
  bio: mx
  avatar: fjrr_mini.jpg # 160x160px author inline
  disqus-shortname: fenandosr


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
